name: Deploy to EC2

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact from previous workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ci.yml
          name: build-artifacts
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY_RAW }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy files to EC2
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no \
            fitness-ai-app.tar docker-compose.yml .env.runtime \
            ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Run Docker Compose on EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu
            docker load < fitness-ai-app.tar
            docker compose down || true
            docker compose up -d
          EOF
